DROP TABLE Promotions_tab CASCADE CONSTRAINTS;
DROP TABLE OfertyWakacyjne_tab CASCADE CONSTRAINTS;
DROP TABLE Kategorie_tab CASCADE CONSTRAINTS;
DROP TABLE Atrakcja_tab CASCADE CONSTRAINTS;
DROP TABLE Oceny_hoteli_tab CASCADE CONSTRAINTS;
DROP TABLE Hotel_tab CASCADE CONSTRAINTS;
DROP TABLE Adresy_tab CASCADE CONSTRAINTS;
DROP TABLE Uzytkownicy_tab CASCADE CONSTRAINTS;